### ISSUE TITLE
Reverse for 'album_detail' with arguments '(1, '')' not found. 1 pattern(s) tried: ['album/(?P<pk>[0-9]+)/(?P<slug>[^/]+)/$']

### ISSUE THREAD

**Issue by demian18** [Starcross/django-starcross-gallery#5] opened 2020-08-05 18:51 UTC
Hi, I really liked your project. I want to create my site with such a gallery.
I want to say the following, after adding images and gallery I got an error -------

NoReverseMatch at /
Reverse for 'album_detail' with arguments '(1, '')' not found. 1 pattern(s) tried: ['album/(?P<pk>[0-9]+)/(?P<slug>[^/]+)/$']

What is causing this error? Help me please

**Comment by demian18** [comment] 2020-08-05 20:05
oops, I found an error because I named the album in my native language (rus). But now the image just doesn't show

**Comment by Starcross** [comment] 2020-08-16 15:17
Hi there, I think this may be caused by the django slugify utility not handling the characters correctly. I can enable it's unicode option to try to fix this. Could you send me an example of a filename and album name you are using?

The best way to fix images producing these errors for now would just be to delete them in the django admin site if possible, and add again with latin1 characters.

**Comment by demian18** [comment] 2020-08-18 10:47
Sorry, but I didn't quite understand what exactly needs to be sent. 

Thank you very much for answering the questions. Hope you answer again in the future

**Comment by Starcross** [comment] 2020-09-12 09:59
Hi again, I have applied a fix for this and tested using Cyrillic characters. It seems to work ok with this unicode flag enabled.

It's available as the latest version 1.0.9

**Comment by demian18** [comment] 2020-09-15 15:54
Hello to you too, thanks for fixing such an unnecessary detail. Someday I'll figure it out myself)))
If i have any more questions, I hope you can help)

**Comment by Starcross** [comment] 2020-10-11 18:42
Thanks

**Closed by Starcross** 2020-10-11 18:42 UTC
